#!/usr/bin/env bash
# Sends a ping 5 times
# Check if an argument was provided
if [ $# -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Ping the IP address
ping -c 5 "$ip_address"
